# Generated by Django 2.2.6 on 2019-10-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191007_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hasImage',
            field=models.BooleanField(default=False),
        ),
    ]
