# Generated by Django 2.2.6 on 2019-10-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20191020_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='hello', max_length=20),
        ),
    ]
