# Generated by Django 2.2.6 on 2019-10-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Uploaded Image'),
        ),
    ]
