# Generated by Django 2.2.6 on 2019-10-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20191020_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='markdown',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
